name: Docker Images Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Check Out Repo
      uses: actions/checkout@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_TOKEN }}

    - name: Build and Push webbapp.hf
      uses: docker/build-push-action@v2
      with:
        context: ./src/webapp.hf
        file: ./src/webapp.hf/Dockerfile
        push: true
        tags: ${{ secrets.DOCKER_HUB_USERNAME }}/webapp.hf:latest
        build-args: |
          <HF_ID>=${{ secrets.HUGGINGFACE_ID }}
          <MODEL_NAME>=${{ secrets.MODEL_NAME }}
          <MODEL_VERSION>=${{ secrets.MODEL_VERSION }}
        
    - name: Build and Push frontend
      uses: docker/build-push-action@v2
      with:
        context: ./src/frontend
        file: ./src/frontend/Dockerfile
        push: true
        tags: ${{ secrets.DOCKER_HUB_USERNAME }}/frontend:latest